### ISSUE TITLE
Equipment module for use as private

### ISSUE THREAD

**Issue by mtorres1** [poctob/OSTicketEquipment#3]
is there a way to use this equipment module internally? For example if categories and equipment are made public then the drop down option for "affected equipment" and "status" show on the front page when someone goes to create a work order. Now we have run into an issue of management not wanting that used publicly but privately.

Front End
They want the user to choose the help topic "vehicles" that management created and that will be linked with a custom form they created.

Back End
They want to be able to edit the ticket and manually attach it to a piece of equipment.
The reason for this is that there will be equipment items that they will want to keep track of how many work orders have been created for that equipment but a user will not necessarily know what to choose - example would be HVAC systems.

so if a user just picks the help topic HVAC - later the facilities manager can edit the ticket and attach it to the HVAC system he has put in as a piece of equipment because he knows which one it is.

If I put everything "internal" all equipment options disappear for use, so it seems the module is just disabled.

I also noticed that with everything enabled and public when you go to edit a ticket the equipment affected has a drop down with no options as image shows.  
![image](https://f.cloud.github.com/assets/6494966/2012724/1bff203a-878c-11e3-86c9-edc48867e8e8.png)

another work around for this would be if it was possible for me to just comment out/delete the snippet of code that adds the "affected equipment" and "status" to the create a new work order page. Then I can leave everything enabled and public and they would not see the options, since it is not a required field I think that should work correct? I just need to know where to do this.

Thanks,
MT

**Comment by poctob** [comment]
Ticket editing was never fully implemented.  It only allows you to change
equipment status if equipment was added to the ticket during initial ticket
creation.  That was a limitation related to the previous osTicket release, but I
think it can be easily fixed now.  It sound like there is enough tweaks to make
a maintenance release.  I'll see if I can get that pushed out in the next couple
days.

Alex Pavlunenko
General Manager
XpressTek LLC.
843-819-2042 (direct)
843-647-7045 (office)
www.xpresstek.net

**Comment by mtorres1** [comment]
Great, I look forward to it. 

Thank You!!

**Comment by poctob** [comment]
New release has been pushed out.  Should fix these issues.

**Comment by mtorres1** [comment]
WOW! you are just awesome, seriously ... I will be installing in a few min - will keep you posted once they start testing. Thank You again.

**Comment by mtorres1** [comment]
OK, let me know if I did something wrong. I stopped the website, unzipped files and put into root as usual and started site. I went in to the admin panel and checked for the back end only
![image](https://f.cloud.github.com/assets/6494966/2023864/d303fc62-8861-11e3-9913-005267818d0b.png)
I made my categories and equipment internal "private"
![image](https://f.cloud.github.com/assets/6494966/2023873/f57b0286-8861-11e3-811b-5e0b73cee26e.png)
I created a test ticket and went into staff panel, edited my ticket but I don't see anything about the equipment as far as attaching it to any equipment and so forth
![image](https://f.cloud.github.com/assets/6494966/2023901/69adfed8-8862-11e3-8721-4aec624acf2e.png)

**Comment by mtorres1** [comment]
I got it working, thanks for everything. :)

**Comment by mtorres1** [comment]
I made everything public at which point the ability to edit a ticket and add equipment showed up while only the back end equipment was checked in admin panel (I thought I got it to work). BUT the equipment affected is still showing on the front end because I had to make everything public in order for the ability to edit a ticket and add equipment to work. How do I stop that section from showing up?
![image](https://f.cloud.github.com/assets/6494966/2034116/5144b1ec-8926-11e3-80a1-c7c5ec6da2d9.png)

**Comment by poctob** [comment]
I made some changes. 

Changed only published equipment to be shown on the front end.
Backend can view all equipment now.
Fixed equipment showing up in the front end during ticket creation even when it is turned off in the settings.

Latest commit:

https://github.com/poctob/OSTicketEquipment/archive/master.zip

**Comment by mtorres1** [comment]
I have been out the last couple of days, I will be doing this today and I will keep you posted. Thanks a ton!!

**Comment by mtorres1** [comment]
OK - not sure why this module would have anything to do with this but when I add the new files the facilities team no longer gets email notifications when a new work order is created. The department manager gets the emails but the staff in the proper group no longer get the email.

 The issue literally started right after I added the new files. Once I put the old files back the email notification started again. Any idea on what is causing this? All settings are correct through out the system and everything is checked or unchecked as needed especially in alerts and notices.

**Comment by mtorres1** [comment]
I made 
![image](https://f.cloud.github.com/assets/6494966/2078554/74b6dd06-8dbf-11e3-8197-5ffd80039371.png)
![image](https://f.cloud.github.com/assets/6494966/2078561/816daec6-8dbf-11e3-9ebf-782695a6e783.png)

**Comment by poctob** [comment]
Can you check if you are getting any php errors in the logs? 
Another thing to try is replacing files one by one to narrow down what could be causing this issue.

**Comment by mtorres1** [comment]
OK, is there anything that was changed that you think might be the problem just so I can have a place to start? I will replace things one at a time like a did before but would help if you have any suspicions.

**Comment by poctob** [comment]
not really sure, it seems to be totally unrelated to the plugin.  Was the email working with the previous release of the plugin?

You can start with these files:
include/staff/ticket-open.inc.php
include/class.ticket.php
include/class.config.php

**Comment by mtorres1** [comment]
Yes it was that's what I found odd, a couple min after changing it the facilities manager called me because he noticed the assistant was not getting any of the new ticket alerts. I put the files back and it worked again. its almost like the group membership option even though it is clicked it not actually working

![image](https://f.cloud.github.com/assets/6494966/2079492/208cf3a8-8dcb-11e3-8949-d8b17445d6ad.png)

I will check out those files

**Comment by mtorres1** [comment]
everything has been working great -- THANK YOU FOR ALL THE SUPPORT -MT

**Comment by poctob** [comment]
did you ever track down the email problem?

**Comment by mtorres1** [comment]
no - no matter what I did I was unable to send to more then just the manager of the department. I eventually created a distribution group and put everyone who needed new ticket alerts in it - then I created a new user in osticket and used that email.

When I tried to add that email to a current user it would not work for some reason. Something happen to the DB but since I found the work around and everything is fine I have not spent anymore time on it.
